spring:
  application:
    name: "customers"
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: "configserver:http://localhost:8070/"
  h2:
    console:
      enabled: true
  mail:
    username: placeholder
    password: placeholder
    host: smtp.gmail.com
    port: 587
  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: true
          brokers: localhost:9092
      bindings:
        customerRegistered-out-0:
          destination: transakt.customer-registered
        customerVerified-out-0:
          destination: transakt.customer-verified

keycloak:
  url: http://localhost:7080
  realm: transakt
  client-id: user-manager
  client-secret: E1LBqeOvGDGxEec0EIxQn9quI70eTI9L # NOTE: Without a persistent keycloak DB, this needs to be regenerated every time the keycloak container restarts.

app:
  frontend-base-url: "http://placeholder.com"

server:
  port: 8080

logging:
  level:
    com:
      cdcrane:
        customers: info

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8075/eureka/