spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:postgresql://localhost:5433/transakt
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: "configserver:http://localhost:8070/"
  h2:
    console:
      enabled: true
  cloud:
    function:
      definition: customerRegistered;customerVerified
    stream:
      kafka:
        binder:
          autoCreateTopics: true
          brokers: localhost:9092
      bindings:
        customerRegistered-in-0:
          destination: transakt.customer-registered
          group: ${spring.application.name}
        customerVerified-in-0:
          destination: transakt.customer-verified
          group: ${spring.application.name}


server:
  port: 8090

logging:
  level:
    com:
      cdcrane:
        transakt:
          accounts: info

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8075/eureka/