spring:
  application:
    name: "transactions"
  datasource:
    url: jdbc:postgresql://localhost:5433/transakt
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: "configserver:http://localhost:8070/"
  cloud:
    function:
      definition: accountOpened
    stream:
      kafka:
        binder:
          autoCreateTopics: true
          brokers: localhost:9092
      bindings:
        accountOpened-in-0:
          destination: transakt.account-opened

logging:
  level:
    com:
      cdcrane:
        transakt:
          transactions: info
    org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry: ERROR


server:
  port: 8100

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8075/eureka/